name: Deploy to Hugging Face

on:
  release:
    types: [created]  # Trigger the workflow when a new release is created

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Get the repository content

      - name: Configure Git and Create .netrc
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}  # Your Hugging Face API token
        run: |
          # Configure Git user details
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Create a .netrc file for Git authentication with Hugging Face
          # Replace 'Alibrown' with your actual Hugging Face username if different
          echo -e "machine huggingface.co\nlogin Alibrown\npassword ${HF_API_TOKEN}" > ~/.netrc
          chmod 600 ~/.netrc  # Secure the file permissions

      - name: Push to Hugging Face Spaces
        run: |
          # Add the remote for Hugging Face Spaces (adjust username/repo as needed)
          git remote add hf https://huggingface.co/spaces/Alibrown/Git-Deploy-to-Hugging-Face
          # Push the current branch to Hugging Face (adjust branch if necessary)
          git push hf HEAD:main

      - name: Deployment Success
        run: echo "Deployment to Hugging Face was successful! 🚀"
