name: Deploy to Hugging Face

on:
  release:
    types: [created]  # Trigger the workflow when a new release is created

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Get the repository content

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Authenticate and Push to Hugging Face
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}  # Access the Hugging Face API token securely
        run: |
          # Use the Hugging Face API token for authentication
          git remote add hf https://user:${HF_API_TOKEN}@huggingface.co/spaces/Alibrown/Git-Deploy-to-Hugging-Face
          git push hf HEAD:main  # Adjust the branch name if needed

          # For Model Repository:
          # git remote add hf https://user:${HF_API_TOKEN}@huggingface.co/models/<username>/<repo>
          # git push hf HEAD:main  # Adjust the branch name if needed

          # For Dataset Repository:
          # git remote add hf https://user:${HF_API_TOKEN}@huggingface.co/datasets/<username>/<repo>
          # git push hf HEAD:main

      # Optional: Add a post-deployment success message
      - name: Deployment Success
        run: echo "Deployment to Hugging Face was successful! 🚀"
