name: Deploy to Hugging Face

on:
  release:
    types: [created]  # Trigger the workflow when a new release is created

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Check out the repository

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Hugging Face Spaces using Token in URL
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}  # Your Hugging Face API token
        run: |
          # Add the remote with the token embedded in the URL (note the .git suffix)
          git remote add hf https://Alibrown:${HF_API_TOKEN}@huggingface.co/spaces/Alibrown/Git-Deploy-to-Hugging-Face.git
          # Push the current branch to Hugging Face (adjust branch name if needed)
          git push hf HEAD:main

      - name: Deployment Success
        run: echo "Deployment to Hugging Face was successful! 🚀"
        
      # ------------------------------------------------------------------
      # Uncomment the following sections if you want to deploy to other repository types:
      
      # For Model Repository:
      # - name: Push to Hugging Face Model Repository
      #   env:
      #     HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
      #   run: |
      #     git remote add hf https://Alibrown:${HF_API_TOKEN}@huggingface.co/models/<username>/<repo>.git
      #     git push hf HEAD:main

      # For Dataset Repository:
      # - name: Push to Hugging Face Dataset Repository
      #   env:
      #     HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
      #   run: |
      #     git remote add hf https://Alibrown:${HF_API_TOKEN}@huggingface.co/datasets/<username>/<repo>.git
      #     git push hf HEAD:main
